import type { Metadata } from "next";
import Image from "next/image";
import { ArrowRight, Bath, BedDouble, BriefcaseBusiness, Check, CircleHelp, Clock3, CookingPot, ExternalLink, HeartPulse, House, Info, Leaf, MapPin, Mountain, PackageCheck, ShowerHead, Sparkles, Trees, Users, Waves } from "lucide-react";
import Link from "@/components/static-link";
import { MobileCta } from "@/components/mobile-cta";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { siteConfig } from "@/data/site";
import { packingList, refundPolicy, stayFacilities, stayFaqs, stayModes, stayPrograms, stayRooms, stayRules } from "@/data/stay";

const pageUrl = "https://hongcheon-yeolmokeo.vercel.app/stay";

export const metadata: Metadata = {
  title: { absolute: "홍천 열목어마을 숙소｜숲·계곡 가까운 독채와 치유여행 숙박" },
  description: "홍천 열목어마을의 보금자리 독채, 비움센터, 한옥 숙소와 워케이션 객실을 소개합니다. 객실과 프로그램, 치유밥상을 연결한 개인·가족·단체 숙박을 상담해 드립니다.",
  keywords: ["홍천 숙소", "홍천 독채 숙소", "홍천 한옥 숙소", "홍천 단체 숙소", "홍천 워케이션", "홍천 치유여행", "홍천 농촌체험 숙소", "홍천 계곡 숙소", "홍천 가족 숙소", "강원도 힐링 숙소"],
  alternates: { canonical: pageUrl },
  openGraph: { title: "홍천 열목어마을 숙소｜숲·계곡 가까운 독채와 치유여행 숙박", description: "보금자리 독채, 비움센터, 한옥 숙소와 워케이션 체류 방식을 비교하고 숙박·치유 프로그램을 함께 상담하세요.", url: pageUrl, type: "website", locale: "ko_KR", siteName: "홍천 열목어마을", images: [{ url: "/images/stay-room.png", width: 1200, height: 630, alt: "숲이 보이는 홍천 열목어마을 숙박 공간" }] },
};

function FacilityIcon({ name }: { name: string }) {
  if (name.includes("업무")) return <BriefcaseBusiness aria-hidden="true" />;
  if (name.includes("숲")) return <Trees aria-hidden="true" />;
  if (name.includes("계곡")) return <Waves aria-hidden="true" />;
  if (name.includes("식사")) return <CookingPot aria-hidden="true" />;
  if (name.includes("주차")) return <MapPin aria-hidden="true" />;
  return <House aria-hidden="true" />;
}

export default function StayPage() {
  const breadcrumbJson = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "홈", item: "https://hongcheon-yeolmokeo.vercel.app/" }, { "@type": "ListItem", position: 2, name: "숙소", item: pageUrl }] };
  const lodgingJson = { "@context": "https://schema.org", "@type": "LodgingBusiness", name: "홍천 열목어마을 숙소", url: pageUrl, description: "홍천의 숲과 계곡 가까이에서 독채, 한옥, 프로그램 연계 체류를 상담할 수 있는 열목어마을 숙소", address: { "@type": "PostalAddress", streetAddress: "내면 명개로 98", addressLocality: "홍천군", addressRegion: "강원특별자치도", addressCountry: "KR" } };
  const faqJson = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: stayFaqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };

  return <><SiteHeader /><main className="stay-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJson) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(lodgingJson) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJson) }} />

    <section className="stay-hero" aria-labelledby="stay-title"><Image src="/images/stay-room.png" alt="창밖으로 홍천 산촌의 숲이 보이는 열목어마을 숙박 공간" fill priority sizes="100vw" /><div className="stay-hero-shade" /><div className="container stay-hero-content"><p className="stay-eyebrow">숲과 계곡 가까이에서 보내는 조용한 밤</p><h1 id="stay-title">잘 쉬어야,<span>다시 힘차게 시작할 수 있습니다</span></h1><p>홍천의 맑은 공기와 자연의 소리를 가까이에서 느끼며 편안한 밤을 보내세요. 독채 숙소부터 프로그램과 연결되는 체류 공간까지 방문 목적에 맞게 안내해 드립니다.</p><div className="stay-hero-actions"><a className="button button-light" href="#rooms">숙소 둘러보기 <ArrowRight size={18} /></a><Link className="button button-ghost" href="/contact?type=stay">예약 상담하기</Link></div></div></section>

    <section className="stay-section stay-features" aria-labelledby="stay-features-title"><div className="container"><div className="stay-heading"><p className="section-kicker">STAY IN NATURE</p><h2 id="stay-features-title">자연 가까이에서 편안하게 머무는 방법</h2><p>일반 관광숙소가 아니라 숲, 계곡, 치유 프로그램과 지역 밥상을 함께 경험할 수 있는 체류형 공간입니다.</p></div><div className="stay-feature-grid">{[{ icon: Mountain, title: "조용한 산촌 환경", text: "자연의 소리에 귀 기울이는 밤" }, { icon: House, title: "독채와 소규모 객실", text: "동행과 목적에 맞는 공간 선택" }, { icon: HeartPulse, title: "치유 프로그램 연계", text: "숲·계곡·명상·족욕을 함께 상담" }, { icon: CookingPot, title: "건강한 식사 선택 가능", text: "식사 포함 여부는 패키지별 상이" }].map(({ icon: Icon, title, text }) => <article key={title}><Icon aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className="stay-section stay-rooms" id="rooms" aria-labelledby="stay-rooms-title"><div className="container"><div className="stay-heading"><p className="section-kicker">ROOM TYPES</p><h2 id="stay-rooms-title">누구와 머무느냐에 따라 선택하세요</h2><p>확인된 객실 구성과 전용·공용 시설을 구분했습니다. 가격과 현재 예약 가능 여부는 상담으로 확인합니다.</p></div><div className="stay-room-grid">{stayRooms.map((room, index) => <article className="stay-room-card" id={`room-${room.id}`} key={room.id}><div className="stay-photo-placeholder" role="img" aria-label={`${room.name} 실제 객실 사진 준비 중`}><span>ROOM {String(index + 1).padStart(2, "0")}</span><House aria-hidden="true" /><strong>실제 사진 준비 중</strong><small>운영자 확인 사진으로 교체 예정</small></div><div className="stay-room-card-body"><p className="stay-room-tag">{room.tag}</p><h3>{room.name}</h3><p className="stay-room-summary">{room.summary}</p><dl className="stay-room-facts"><div><dt><BedDouble size={17} /> 객실 구성</dt><dd>{room.roomConfigurations.join(" · ")}</dd></div><div><dt><Bath size={17} /> 화장실</dt><dd>{room.privateBathroom === null ? "운영자 확인 중" : room.privateBathroom ? "객실 내 단독" : "비움센터 내 공용"}</dd></div><div><dt><ShowerHead size={17} /> 샤워실</dt><dd>{room.privateShower === null ? "운영자 확인 중" : room.privateShower ? "객실 내 단독" : "비움센터 내 공용"}</dd></div></dl><div className="stay-recommend"><b>이런 분께 추천</b><span>{room.recommendedFor.join(" · ")}</span></div>{room.inventoryNote && <p className="stay-confirm-note"><Info size={16} /> {room.inventoryNote}</p>}<div className="stay-card-actions"><a className="button button-outline" href={`#detail-${room.id}`}>상세 보기</a><Link className="button button-primary" href={`/contact?type=stay&room=${room.id}`}>이 숙소 문의하기</Link></div></div><span id={`detail-${room.id}`} className="stay-anchor" /></article>)}</div></div></section>

    <section className="stay-section stay-compare" aria-labelledby="stay-compare-title"><div className="container"><div className="stay-heading"><p className="section-kicker">COMPARE</p><h2 id="stay-compare-title">객실 한눈에 비교</h2><p>빈칸 없이 확인 상태까지 함께 보여드립니다.</p></div><div className="stay-table-wrap"><table><thead><tr><th>비교 항목</th>{stayRooms.map(room => <th key={room.id}>{room.name}</th>)}</tr></thead><tbody>
      <tr><th>숙소 유형</th>{stayRooms.map(room => <td key={room.id}>{room.type}</td>)}</tr><tr><th>추천 대상</th>{stayRooms.map(room => <td key={room.id}>{room.recommendedFor.join("·")}</td>)}</tr><tr><th>기준 인원</th>{stayRooms.map(room => <td key={room.id}>{room.roomConfigurations.join(" · ")}</td>)}</tr><tr><th>독채 여부</th>{stayRooms.map(room => <td key={room.id}>{room.id === "bogumjari" || room.id === "hanok" ? "독채" : room.id === "bieum-center" ? "공용시설 연계" : "구성 확인 필요"}</td>)}</tr><tr><th>화장실</th>{stayRooms.map(room => <td key={room.id}>{room.privateBathroom === true ? "객실 내 단독" : room.privateBathroom === false ? "센터 내 공용" : "운영자 확인 중"}</td>)}</tr><tr><th>샤워실</th>{stayRooms.map(room => <td key={room.id}>{room.privateShower === true ? "객실 내 단독" : room.privateShower === false ? "센터 내 공용" : "운영자 확인 중"}</td>)}</tr><tr><th>업무공간 접근성</th>{stayRooms.map(room => <td key={room.id}>{room.workAccess}</td>)}</tr><tr><th>프로그램 공간</th>{stayRooms.map(room => <td key={room.id}>{room.programAccess}</td>)}</tr><tr><th>가격</th>{stayRooms.map(room => <td key={room.id}>상담 시 안내</td>)}</tr><tr><th>현재 예약 가능 여부</th>{stayRooms.map(room => <td key={room.id}>운영자 확인 중</td>)}</tr>
    </tbody></table></div><div className="stay-mobile-compare">{stayRooms.map(room => <article key={room.id}><h3>{room.name}</h3><dl><div><dt>유형</dt><dd>{room.type}</dd></div><div><dt>객실</dt><dd>{room.roomConfigurations.join(" · ")}</dd></div><div><dt>화장실·샤워실</dt><dd>{room.privateBathroom === true ? "객실 내 단독" : room.privateBathroom === false ? "비움센터 내 공용" : "운영자 확인 중"}</dd></div><div><dt>가격</dt><dd>상담 시 안내</dd></div><div><dt>예약 가능 여부</dt><dd>운영자 확인 중</dd></div></dl><Link href={`/contact?type=stay&room=${room.id}`} className="text-link">객실 문의 <ArrowRight size={16} /></Link></article>)}</div></div></section>

    <section className="stay-section stay-modes" aria-labelledby="stay-modes-title"><div className="container"><div className="stay-heading"><p className="section-kicker">YOUR WAY TO STAY</p><h2 id="stay-modes-title">원하는 여행 방식으로 머물러 보세요</h2><p>숙박만, 치유여행, 워케이션, 단체 체류까지 목적을 알려주시면 가능한 구성을 확인해 드립니다.</p></div><div className="stay-mode-grid">{stayModes.map((mode, index) => <article key={mode.id}><span>{String(index + 1).padStart(2, "0")}</span><h3>{mode.title}</h3><p>{mode.text}</p><small>{mode.note}</small><Link className="button button-outline" href={`/contact?type=${mode.query}&stayMode=${mode.id}`}>상담하기</Link></article>)}</div></div></section>

    <section className="stay-section stay-facilities" aria-labelledby="stay-facilities-title"><div className="container"><div className="stay-heading"><p className="section-kicker">BEYOND THE ROOM</p><h2 id="stay-facilities-title">객실 밖에서도 쉼은 이어집니다</h2><p>기존 자료에서 확인된 시설과 현장 운영 확인이 필요한 시설을 구분했습니다.</p></div><div className="stay-facility-grid">{stayFacilities.map(facility => <article key={facility.name}><FacilityIcon name={facility.name} /><div><p className={facility.verified ? "stay-verified" : "stay-pending"}>{facility.verified ? "자료 확인" : "운영자 확인 필요"}</p><h3>{facility.name}</h3><p>{facility.usageNotes}</p><small>숙박 포함 여부: {facility.includedWithStay === null ? "상품별 확인" : facility.includedWithStay ? "포함" : "별도"}</small></div></article>)}</div></div></section>

    <section className="stay-section stay-programs" aria-labelledby="stay-programs-title"><div className="container stay-program-layout"><div className="stay-program-media"><Image src="/images/singing-bowl.png" alt="홍천 열목어마을 숲속 치유 프로그램에서 사용하는 싱잉볼" fill sizes="(max-width: 900px) 100vw, 48vw" /><div><Image src="/images/healing-table.jpg" alt="홍천 제철 식재료로 차린 열목어마을 치유밥상" fill sizes="(max-width: 900px) 45vw, 20vw" /></div></div><div><p className="section-kicker">STAY &amp; HEALING</p><h2 id="stay-programs-title">잠만 자는 숙박보다,<br />제대로 쉬는 체류를 경험하세요</h2><p>프로그램은 계절, 인원, 방문 목적에 따라 달라질 수 있습니다. 숙박 예약 전 원하는 체험을 함께 문의해 주세요.</p><div className="stay-program-pills">{stayPrograms.map(program => <span key={program}><Leaf size={15} />{program}</span>)}</div><div className="stay-inline-actions"><Link href="/programs" className="button button-outline">치유 프로그램 보기</Link><Link href="/contact?type=stay-package" className="button button-primary">숙박 패키지 상담</Link></div></div></div></section>

    <section className="stay-section stay-guide" aria-labelledby="stay-guide-title"><div className="container"><div className="stay-heading"><p className="section-kicker">HOUSE GUIDE</p><h2 id="stay-guide-title">편안한 숙박을 위한 이용안내</h2><p>기존 공식 숙박 이용안내에서 확인한 기준입니다. 예약 상품의 최종 안내를 다시 확인해 주세요.</p></div><div className="stay-rule-list">{stayRules.map((rule, index) => <details key={rule.title} open={index === 0}><summary><span>{rule.title}</span><CircleHelp size={20} /></summary><ul>{rule.items.map(item => <li key={item}><Check size={16} />{item}</li>)}</ul></details>)}</div></div></section>

    <section className="stay-section stay-packing" aria-labelledby="stay-packing-title"><div className="container stay-packing-layout"><div><p className="section-kicker">PACKING LIST</p><h2 id="stay-packing-title">방문 전 준비해 주세요</h2><p>산촌의 날씨와 야외 활동을 고려해 가볍지만 빠짐없이 준비해 주세요.</p></div><div className="stay-packing-list">{packingList.map(item => <span key={item}><PackageCheck size={20} />{item}</span>)}</div><p className="stay-amenity-alert"><Info size={20} /><span><b>욕실용품은 상품별로 확인해 주세요.</b> 수건과 욕실용품 제공 여부는 객실 및 숙박 상품에 따라 다를 수 있습니다. 예약 확정 전 제공 물품을 확인해 주세요.</span></p></div></section>

    <section className="stay-section stay-booking" aria-labelledby="stay-booking-title"><div className="container"><div className="stay-booking-intro"><p className="section-kicker">BOOKING GUIDE</p><h2 id="stay-booking-title">예약 전 세 가지만 알려주세요</h2><div><span><Clock3 />희망 방문 날짜</span><span><Users />방문 인원과 구성</span><span><Sparkles />프로그램 참여 여부</span></div><p>실시간 객실 재고가 연결되어 있지 않아 문의 후 객실 가능 여부를 확인합니다.</p></div><ol className="stay-booking-flow">{["객실과 체류 방식 선택", "날짜·인원 문의", "객실 가능 여부 확인", "프로그램·식사 구성 상담", "금액 및 결제 안내", "예약 확정"].map((step, index) => <li key={step}><span>{index + 1}</span><b>{step}</b></li>)}</ol><div className="stay-booking-actions"><Link className="button button-primary" href="/contact?type=stay">객실 가능 여부 문의</Link><Link className="button button-outline" href="/contact?type=stay-package">숙박 상담 신청</Link><Link className="button button-outline" href="/contact?type=group-stay">단체 견적 요청</Link></div>{siteConfig.reservationUrl && <a className="stay-external-booking" href={siteConfig.reservationUrl} target="_blank" rel="noreferrer">네이버 예약 <ExternalLink size={16} /></a>}<div className="stay-refund"><div><p className="section-kicker">CANCELLATION</p><h3>취소·환불 안내</h3><p>아래 규정은 기존 공식 안내를 기준으로 작성되었습니다. 예약 상품에 따라 적용 기준이 달라질 수 있으므로 결제 전 최종 규정을 확인해 주세요.</p></div><table><thead><tr><th>취소 시점</th><th>기존 안내 기준</th></tr></thead><tbody>{refundPolicy.map(([when, amount]) => <tr key={when}><td>{when}</td><td>{amount}</td></tr>)}</tbody></table></div></div></section>

    <section className="stay-section stay-faq" aria-labelledby="stay-faq-title"><div className="container"><div className="stay-heading"><p className="section-kicker">FAQ</p><h2 id="stay-faq-title">숙소 이용 전 자주 묻는 질문</h2><p>현재 확정되지 않은 내용은 상담이 필요하다고 명확히 안내합니다.</p></div><div className="stay-faq-list">{stayFaqs.map(([question, answer]) => <details key={question}><summary>{question}<span>＋</span></summary><p>{answer}</p></details>)}</div><div className="stay-related-links"><Link href="/programs">치유 프로그램</Link><Link href="/group">단체·워크숍</Link><Link href="/guide">여행 안내</Link><Link href="/contact">문의하기</Link></div></div></section>

    <section className="stay-final" aria-labelledby="stay-final-title"><Image src="/images/forest-1.jpg" alt="홍천 열목어마을 숙소 주변의 산과 산촌 풍경" fill sizes="100vw" /><div className="stay-final-shade" /><div className="container"><p>오늘은 조금 천천히 쉬어도 괜찮습니다</p><h2 id="stay-final-title">홍천의 깊은 밤과<span>맑은 아침을 만나보세요</span></h2><b>숙소 유형과 방문 인원, 프로그램 참여 여부를 알려주시면 가장 적합한 체류 방법을 안내해 드립니다.</b><div><Link className="button button-light" href="/contact?type=stay">객실 가능 여부 문의</Link><Link className="button button-ghost" href="/contact?type=stay-package">숙박 패키지 상담</Link><Link className="button button-ghost" href="/contact?type=group-stay">단체 숙박 견적</Link></div></div></section>
  </main><SiteFooter /><MobileCta /></>;
}
